- src/components/common/tag/Tag.tsx
- src/components/common/tag/tag.module.css
- src/pages/testpage.tsx
> [Feature/tag] 색상 랜덤 구현하기

- src/api/services/authServices.ts
- src/api/services/cardsServices.ts
- src/api/services/columnsServices.ts
- src/api/services/commentsServices.ts
- src/api/services/dashboardsServices.ts
- src/api/services/invitationsServices.ts
- src/api/services/membersServices.ts
- src/api/services/usersServices.ts
- src/pages/_app.tsx
- src/types/api/auth.ts
- src/types/api/cards.ts
- src/types/api/columns.ts
- src/types/api/comments.ts
- src/types/api/dashboards.ts
- src/types/api/invitations.ts
- src/types/api/menmbers.ts
- src/types/api/users.ts
- src/types/common/error.ts
- src/utils/handleError.ts
API 기능 전체 구현 완료
- `authService.ts`: 로그인, 비밀번호 변경 API 구현  
- `cardsService.ts`: 카드 CRUD, 상세 조회 구현  
- `columnsService.ts`: 컬럼 CRUD 및 이미지 업로드 구현  
- `commentsService.ts`: 댓글 CRUD 구현  
- `dashboardsService.ts`: 대시보드 CRUD, 초대 관련 API 구현  
- `invitationsService.ts`: 받은 초대 목록 조회, 초대 수락/거절 구현  
- `membersService.ts`: 멤버 조회, 멤버 삭제 구현  
- `usersService.ts`: 회원가입, 내 정보 조회/수정, 이미지 업로드 구현  
- 공통 유틸: `handleError.ts`로 APIError 통일
- 모든 API 요청에 accessToken 인증 적용되어 있습니다.  
- 일부 API TEST 문제 없이 진행되었습니다.
- 추후에 API 사용하다가 오류 생기면 알려주세요!
> ✨[Feature] Swagger 기반 API 모듈 전면 구현

- src/components/layout/sidebar/sidebar.module.css
- src/pages/mypage.module.css
- src/pages/mypage.tsx
mypage에서 Navbar를 추가 시켰고, 피그마와 동일한 위치로 수정하였습니다.
- [] 1기능에 대한 구체 내용 기술 
> [Fix/ mypage] 위치 조정 및 navbar 추가

- package-lock.json
- src/components/layout/layout.tsx
- src/pages/dashboard/[id]/index.tsx
homenavbar와 sidebar, 본문 배경색을 포함한 Layout 컴포넌트 구현
- 보기 쉬울 수 있도록 dashboard의 경우엔 Layout 컴포넌트를 적용해둔 상태입니다.
- homenavbar의 경우에 간격 재조정이 필요한 것 같습니다.
> [Feature/layout] homenavbar와 sidebar, 본문 배경색을 포함한 Layout 컴포넌트 구현

- src/components/common/commonbutton/CommonButton.tsx
- src/components/domain/modals/dashboardCreateModal/DashboardCreateModal.tsx
mydashboard 모달 API 기능 구현 및 버튼 공통 컴포넌트명 수정
JIRA - SCRUM 78, 79, 81
* 현재 Button 컴포넌트와 Input 컴포넌트가 이름이 변경됨에 따라 전반적인 리팩토링이 진행 되어야 할 것 같은데, 다른 파일을 건드리면 충돌이 너무 날까봐 진행을 하지 못하고 있습니다..! **merge 할 수 있는 부분을 얼른 merge 하고나서 리팩토링** 하는 게 좋지 않을까 싶습니다.
* 수연님이 만들어주신 토큰 로직이 구성 요소 명세표에 명확하게 설명이 안되어있어서 어떻게 사용해야 할 지 잘 모르겠네요 ㅜㅠㅠ **로직 구현은 끝났고, 설명 듣고 토큰 받아서 테스팅 해보면 될 것 같습니다.**
> [Feature/mydashboard-modal-api] mydashboard 모달 API 기능 구현 및 버튼 공통 컴포넌트명 수정

- src/components/common/tag/Tag.tsx
- src/components/domain/modals/TaskCardEditModal.tsx
태그 x 버튼 삭제 기능 추가
- 태그 x 버튼 삭제 기능 추가
- Tag 컴포넌트 만드신 찬영님께 허락을 구한 뒤에 컴포넌트 내에 x 버튼을 추가하였습니다.
> [Feature/tag-x-button] 태그 x 버튼 삭제 기능 추가

- src/pages/login/index.tsx
- src/pages/mypage.tsx
- src/pages/signup/index.tsx
develop에서 이상한 부분 수정 
로그인
회원가입 
마이페이지
layout 컴포넌트로 마이페이지 재구성
모달 파일 이동으로 인해 로그인, 회원가입 창 안 들어가진거 다시 고침
변경된 UI가 있다면 스크린
샷을 첨부해주세요.
1. develop 로그인 페이지 못 들어가는 이슈 발생(이거 안되면 모든 페이지 다 안됨)
2. 홈페이지 + 마이페이지 수정
develop 브랜치가 현재 이상합니다. 이거 빠르게 머지해야할 것 같아요, 이게 정상본이에요,
> [hotfix/loginrefactor] develop 이상한 부분 수정

- src/api/services/authServices.ts
- src/api/services/cardsServices.ts
- src/api/services/columnsServices.ts
- src/api/services/commentsServices.ts
- src/api/services/dashboardsServices.ts
- src/api/services/invitationsServices.ts
- src/api/services/membersServices.ts
- src/api/services/usersServices.ts
api 전반에 fetch 예외 대응을 위한 try-catch 블록 추가
반복되는 `BASE_URL`, `Authorization`의 경우 fetch.ts에서 처리해야하나, 이미 짜여진 코드여서 변경하기 모호한 상황이어서 변경 X
> [Refactor/fetch-error-handling] api 전반에 fetch 예외 대응을 위한 try-catch 블록 추가

- src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
- src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
할 일 생성 모달과 할 일 수정 모달에서 사용하지 않는 Custom DatePicker 관련 스타일 코드를 제거하여 컴파일 시 발생하던 오류를 해결하였습니다.
> [Fix/task-card-create-modal-ui]: DatePicker에서 불필요한 className 스타일 제거

- src/components/dropdown/StatusDropdown.tsx
- src/components/dropdown/UserDropdown.tsx
- src/components/dropdown/statusDropdown.module.css
- src/components/dropdown/userDropdown.module.css
> [Style/dropdown]: 드롭 다운 스크롤바, input 스타일 변경 및 tailwind에서 moudle.css로 변경

- src/components/layout/gnb/HomeNavBar.tsx
- src/components/layout/layout.tsx
- src/stores/auth.ts
1. 기존에 있던 layout + zustand + 전역관리 브랜치 코드리뷰 반영하고 푸쉬한줄알았는데.. 안 하고 머지 했었습니다. 그래서 따로 브랜치 만들어서 
코드리뷰 반영해서 다시 머지하려고 합니다.
2. https://github.com/codeit-sprint14-part3-4/Taskify/pull/45 코드리뷰 반영본이라.. 따로 할 말이 없습니다..
**승인해주세요.**
> [chore/codereview layout] layout 코드리뷰 반영본

- src/pages/mypage/index.tsx
현재 develop에 있는 마이페이지 Tailwind CSS 적용 문제 해결
> [Style/mypage]: Style - Tailwind CSS로 다시 적용

- src/components/layout/gnb/homenavbar.module.css
- src/components/layout/sidebar/Sidebar.tsx
- src/pages/mypage.tsx
프로필 이미지 업로드가 되면 깨짐 현상과 모달을 열면 뱃지와 프로필 이미지가 레이아웃의 잡힘
- 해결1: 프로필 이미지 `width`와 `height` 값을 설정하여 깨지지 않게 수정함
- 해결2: 프로필 이미지와  뱃지 `Position`을 해제하여 레이아웃을 제대로 잡히도록 수정함
> [Feature/mypage]: 마이페이지, 사이드바 스켈레톤 UI 구현 및 오류 제거

- src/pages/login.tsx
- src/pages/signup.tsx
1. 로그인 / 회원가입 창은 스켈레톤을 거의 쓰지 않는다고 해서 스핀 모양으로 처리 했습니다. 
1. useState로 로딩 관리하고 이에 맞게 스타일이 변경됩ㄴ디ㅏ
> [feature/login-signup-skeletone] 로그인 / 회원가입중일 때 스핀 모양으로 처리

- src/components/domain/modals/basemodal/FormModal.tsx
- src/components/skeleton/SkeletonMyPage.tsx
- src/pages/mypage.tsx
- src/types/common/formmodal.ts
마이페이지 반응형 및 스켈레톤 UI 적용과 폼 모달 수정
> [Style/mypage]: 마이페이지 반응형 및 스켈레톤 UI 적용, 폼 모달 수정

- src/components/common/commonbutton/pagination.module.css
- src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
- src/components/domain/mydashboard/editmydashboardattribute/editMyDashboardAttribute.module.css
- src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
- src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
- src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
- src/components/domain/mydashboard/editmydashboardmember/editMyDashboardMember.module.css
- src/components/skeleton/SkeletonAttribute.tsx
- src/components/skeleton/SkeletonInviteLog.tsx
- src/components/skeleton/SkeletonMember.tsx
- src/pages/dashboard/[id]/edit/index.tsx
스켈레톤 UI 추가 및 CSS 수정
* 테일윈드 hover 속성이 트러블 슈팅 페이지에 있는 방법 모두 시도 해봤는데 적용이 안되네요 😭 반응형 로직 추가할 때 조금 더 손을 봐야 할 것 같습니다
> [Feat/modify-editPage-requirements] 스켈레톤 UI 추가 및 CSS 수정

- src/components/domain/dashboard/Card.tsx
- src/components/domain/dashboard/card.module.css
- src/components/domain/dashboard/column.module.css
- src/pages/dashboard/[id]/dashboard.module.css
- src/pages/dashboard/[id]/index.tsx
대시보드 반응형 구현
PC
태블릿
모바일
🔖 모바일 버전 : 버튼 내부 아이콘이 .icon { display: none; } 때문에 모바일에서 사라짐
> [Style/dashboard]: dashboard 반응형 구현

- src/components/layout/gnb/HomeNavBar.tsx
- src/components/layout/gnb/homenavbar.module.css
- src/components/layout/layout.module.css
- src/components/layout/layout.tsx
- src/components/layout/sidebar/Sidebar.tsx
- src/components/layout/sidebar/sidebar.module.css
레이아웃 반응형
1. useEffect 써서 +9명 반응형에 따라 달리 함
레이아웃 / 카드 무한 스크롤 브랜치 각각 따로 만들게요잉~
> [feat/layout-card] 레이아웃 반응형

- src/components/domain/mydashboard/dashboardinvitedlist/MyInvitedDashboard.tsx
- src/components/domain/mydashboard/dashboardinvitedlist/myInvitedDashboard.module.css
- src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
- src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
- src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
- src/hooks/useIsMobile.ts
- src/pages/mydashboard.tsx
> [Style/mydashboard style] 마이 대시보드 페이지 스켈레톤 UI및 반응형 구현

- src/components/common/commonbutton/ButtonDashboard.tsx
- src/components/common/commonbutton/CommonButton.tsx
- src/components/common/commonbutton/Pagination.tsx
- src/components/common/commonbutton/pagination.module.css
- src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
- src/components/domain/mydashboard/editmydashboardattribute/editMyDashboardAttribute.module.css
- src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
- src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
- src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
- src/components/domain/mydashboard/editmydashboardmember/editMyDashboardMember.module.css
- src/pages/dashboard/[id]/edit/edit.module.css
- src/pages/dashboard/[id]/edit/index.tsx
editPage 반응형 로직 추가
화면 공유로 대체 하겠습니다!
테일윈드가 적용 되지 않는 부분은 module.css로 추가 했습니다(나쁜 테일윈드 😠)
> [Feature/responsive-editPage] editPage 반응형 로직 추가

- src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
- src/components/domain/modals/taskcardcreatemodal/taskCardCreateModal.module.css
- src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
- src/components/domain/modals/taskcardeditmodal/taskCardEditModal.module.css
- src/components/dropdown/statusDropdown.module.css
- src/pages/dashboard/[id]/index.tsx
> [Style/taskmodal]: 모달 할 일 생성, 수정 반응형 추가

- src/components/skeleton/SkeletonDashboard.tsx
- src/pages/dashboard/[id]/index.tsx
> [Style/dashboard]: 대시보드 스켈레톤 UI 추가

- src/components/common/commonbutton/ButtonDashboard.module.css
- src/components/domain/dashboard/card.module.css
- src/components/domain/dashboard/column.module.css
- src/components/domain/mydashboard/dashboardinvitedlist/myInvitedDashboard.module.css
- src/components/domain/mydashboard/dashboardlist/DashboardListButton.tsx
- src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
- src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
- src/components/dropdown/DropdownPortal.tsx
- src/components/dropdown/MyDropDown.tsx
- src/components/dropdown/myDropdown.module.css
- src/components/layout/gnb/HomeNavBar.tsx
- src/components/layout/gnb/homenavbar.module.css
- src/pages/login.tsx
1. 홈내브바 드롭다운 위치 선정 (모바일일때는 왼쪽으로)
2. 대시보드 버튼 수정 (모바일도 아이콘 잘 보이게)
1. 프로필 드롭다운 위치는 모바일일때는 왼쪽으로 위치합니다. 
2. 대시보드 버튼 수정했는데 그래도 각자 했던 부분 다시 확인해주세요, 제가 나름 보긴 했는데 놓친 부분이 있을 수도 있어요
> [Fix/homenav-button] 홈내브바 드롭다운 수정 + 대시보드 버튼 반응형 수정

- src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
- src/components/domain/modals/taskcardmodal/taskCardModal.module.css
할 일 카드 상세 모달 댓글 무한 스크롤 로직 추가
화면 공유로 대체 했습니다!
ㅠㅠ
> [Feature/task-detail-modal-infinite-scroll] 할 일 카드 상세 모달 댓글 무한 스크롤 로직 추가

- src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
날짜 캘린더 1970.01.01 뜨는 오류 재수정
- x ] 버그 수정
- 날짜 미지정 시, 1970.01.01로 뜨는 오류 수정
> [Fix/calendar] 날짜 캘린더 1970.01.01 뜨는 오류 재수정

- src/components/domain/dashboard/Column.tsx
- src/components/layout/sidebar/Sidebar.tsx
- src/components/layout/sidebar/sidebar.module.css
> [feat/card-limit2] - 카드 무한스크롤

- src/components/domain/modals/dashboardCreateModal/DashboardCreateModal.tsx
- src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
- src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
- src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
- src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
- src/components/layout/layout.tsx
- src/components/layout/sidebar/Sidebar.tsx
- src/pages/dashboard/[id]/edit/index.tsx
- src/pages/dashboard/[id]/index.tsx
- src/pages/mydashboard.tsx
- src/pages/mypage.tsx
- src/pages/signup.tsx
에러 고쳤습니다. 
ㅇ이 부분 이렇게 해도 될까요? alert로 되어있는 것도 있고 에러메세지 쓰는 것도 있어서 일단 통일성있게 에러메세지로 다 통일하긴 했어요
1. 무한 스크롤 안됐어요;;; 따로 브랜치 새로 파서 할게요 + 뱃지랑 같이
2. 이거 머지 되면 이제 에러 없이 하셔야 합니다.
3. 토스트 주석처리 했습니다. 일단 성공/ 수락 등 긍정적인 느낌을 toast로 이용하면 좋을 것 같아서 그 부분 중심으로 주석처리 했습니다.
4. 전체적인 코드 오류를 수정했는데 다시 한번 보시고 자기 코드 이상하면 알려주세요
> [Fix/error] 전체적인 에러 고침 --> 피드백 반영 + 전체적인 오류 고침

- src/components/domain/dashboard/Column.tsx
- src/components/layout/gnb/HomeNavBar.tsx
console.log 제거 및 homenav 수정
콘솔에서 계속 보여 삭제함
> [Style] console.log 제거 및 homeNavbar 수정

- src/components/common/commonbutton/commonButton.module.css
- src/components/domain/dashboard/CardTable.tsx
- src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
- src/components/domain/modals/taskcardcreatemodal/taskCardCreateModal.module.css
- src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
- src/components/domain/modals/taskcardeditmodal/taskCardEditModal.module.css
- src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
- src/components/domain/modals/taskcardmodal/taskCardModal.module.css
- src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
- src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
- src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
- src/components/dropdown/statusDropdown.module.css
- src/components/layout/gnb/HomeNavBar.tsx
- src/components/layout/gnb/gnb.module.css
- src/components/layout/layout.tsx
- src/pages/index.tsx
- src/pages/mydashboard.tsx
에러 사항에 있는 전체적인 css 거의 수정했습니다. 
1. 파일을 많이 만졌습니다. 
2. 머지 하고 싶으시면 하셔도 됩니다.
> [chore/refactor-styles] 전체적인 스타일 수정 

- src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
- src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
- src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
- src/pages/mydashboard.tsx
1. 대시보드 목록 보입니다
2. 목록이 하나도 없을 때도 대시보드 추가 버튼 잘 보입니다 
1. 대시보드 목록 보입니다
2. 목록이 하나도 없을 때도 대시보드 추가 버튼 잘 보입니다 
3. 버튼위치도 고정됩니다. 
1. 머지 하고 싶으시면 하셔도 됩니다.
> [feat/mydashboard-list-button] 대시보드 목록 수정

- src/components/common/commonbutton/buttonDashboard.module.css
- src/components/domain/dashboard/column.module.css
- src/components/domain/modals/taskcardcreatemodal/taskCardCreateModal.module.css
- src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
- src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
- src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
- src/components/domain/mydashboard/editmydashboardattribute/editMyDashboardAttribute.module.css
- src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
- src/components/domain/mydashboard/editmydashboardmember/editMyDashboardMember.module.css
- src/components/layout/gnb/HomeNavBar.tsx
- src/components/layout/gnb/homenavbar.module.css
- src/components/layout/layout.module.css
- src/components/layout/sidebar/sidebar.module.css
- src/pages/dashboard/[id]/dashboard.module.css
- src/pages/dashboard/[id]/edit/edit.module.css
- src/pages/dashboard/[id]/edit/index.tsx
- src/pages/dashboard/[id]/index.tsx
- src/pages/login.tsx
- src/pages/mydashboard.tsx
- src/pages/mypage.tsx
- src/pages/signup.tsx
모바일 전체적으로 css 수정
마이대시보드 마이페이지 등 어색한 부분 처리
1. 모바일쪽 중심으로 수정했습니다. 
1. 모달 쪽 모바일 이상합니다.
> [Feat/mobile] 모바일 전체적으로 css 수정

- src/components/common/badge/Badge.tsx
- src/components/common/tag/Tag.tsx
- src/components/domain/dashboard/Card.tsx
- src/components/domain/dashboard/Column.tsx
- src/components/domain/dashboard/column.module.css
- src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
- src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
- src/components/domain/modals/taskcardmodal/taskCardModal.module.css
- src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
- src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
> [Fix] 에러사항 코드 수정

- src/components/common/badge/Badge.tsx
- src/components/domain/dashboard/Card.tsx
- src/components/domain/dashboard/column.module.css
- src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
- src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
- src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
- src/components/domain/modals/taskcardmodal/taskCardModal.module.css
> [Style/Tag]: 태그 색상 유지

- package-lock.json
- src/components/domain/dashboard/column.module.css
- src/components/domain/modals/taskcardmodal/taskCardModal.module.css
> [Style:card] 카드 모달, Column Title 수정

- src/components/domain/modals/basemodal/baseModal.module.css
- src/components/domain/modals/taskcardcreatemodal/taskCardCreateModal.module.css
- src/components/domain/modals/taskcardeditmodal/taskCardEditModal.module.css
- src/components/domain/mydashboard/dashboardinvitedlist/myInvitedDashboard.module.css
- src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
- src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
- src/components/layout/gnb/HomeNavBar.tsx
- src/components/layout/gnb/homenavbar.module.css
- src/components/layout/layout.module.css
- src/pages/mypage.tsx
모달 반응형
전체적으로 모달 모바일 버전 수정 좀 했습니다. (진짜 핸드폰으로 모달 보면 짱 컸어요)
> [style/modal-mobile] 모바일 모달 수정

- src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
- src/components/domain/modals/taskcardmodal/taskCardModal.module.css
- src/components/layout/layout.module.css
> [feat/comment-bug]댓글수정

- src/pages/_app.tsx
- src/pages/dashboard/[id]/dashboard.module.css
> [fix/css]스크롤수정
